source:      .
destination: ./_site
includes:    ./_includes
plugins:		 ./_plugins

pygments:      true
markdown:      rdiscount
permalink:     /:title.html

name: RoginFarrer.com
base_url: /
url: http://roginfarrer.com
description: "A blog covering Tech news, design, productivity, health, and the arts by Rogin Farrer."
root_desc: "RoginFarrer.com — Tech, Design, and Theater"

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb']
include: ['.htaccess']

paginate: 5