source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:title.html

name: RoginFarrer.com
base_url: ""
description: "A blog covering Tech news, design, productivity, health, and the arts by Rogin Farrer."
root_desc: "RoginFarrer.com — Tech, Design, and Theater"

rdiscount:
  extensions: []
  
exclude: ['Rakefile', 'README.markdown', 'config.rb']

paginate: 5